name: Cypress Tests
on: [push]
jobs:
  parallel-runs:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        machines: [1, 2]
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          parallel: true
          browser: chrome
          headed: true
          start: npx cypress run --record --key 9d400702-0f18-40f3-9b75-fe804e27192c